
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    http: true
    tlsacme: false

db:
  mysqlRootPassword: admin123
  mysqlUser: drupal
  mysqlPassword: 123
  mysqlDatabase: drupal
  fullnameOverride: mysql

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

preview:
  image:
    repository: /caopendata/dharizza/dkan2-jx
    tag:
    pullPolicy: IfNotPresent
  env:
    DKTL_DOCKER: 1
    MYSQL_ROOT_PASSWORD: admin123
    MYSQL_USER: drupal
    MYSQL_PASSWORD: 123
    MYSQL_DATABASE: drupal

